SHORT_SIGNS4 = [
    "Bazaar in Marrakech with a sign that says 'Handcrafted Treasures'",
    "Street market in Tokyo with a sign that says 'Fresh Sushi Rolls'",
    "Plaza in Mexico City with a sign that says 'Fiesta Mexicana'",
    "Café in Paris with a sign that says 'Croissants & Coffee'",
    "Templo in Buenos Aires with a sign that says 'Tango Lessons Tonight'",
    "Night market in Bangkok with a sign that says 'Spicy Thai Street Food'",
    "Beach in Rio de Janeiro with a sign that says 'Caipirinha Happy Hour'",
    "Piazza in Rome with a sign that says 'Gelato Gelato Gelato!'",
    "Tea house in Istanbul with a sign that says 'Turkish Delight Tasting'",
    "Art gallery in Seoul with a sign that says 'Contemporary Korean Art'",
    "Street food stall in Mumbai with a sign that says 'Samosa Special'",
    "Pub in Dublin with a sign that says 'Traditional Irish Music Session'",
    "Chinatown in New York City with a sign that says 'Lunar New Year Celebrations'",
    "Cultural center in Cape Town with a sign that says 'African Drumming Workshop'",
    "Piazza in Florence with a sign that says 'Italian Wine Tasting'",
    "Museum in St. Petersburg with a sign that says 'Russian Folk Art Exhibit'",
    "Cafeteria in Havana with a sign that says 'Cuban Coffee & Pastries'",
    "Floating market in Ho Chi Minh City with a sign that says 'Fresh Fruit Smoothies'",
    "Palace in Jaipur with a sign that says 'Rajasthani Dance Performance'",
    "Market in Casablanca with a sign that says 'Moroccan Tagine Cooking Class'",
    "Café in Vienna with a sign that says 'Viennese Apfelstrudel'",
    "Street festival in Salvador with a sign that says 'Capoeira Demonstrations'",
    "Market in Cairo with a sign that says 'Egyptian Spice Bazaar'",
    "Teahouse in Kyoto with a sign that says 'Traditional Tea Ceremony'",
    "Plaza in Athens with a sign that says 'Greek Souvlaki Festival'",
    "Street food market in Mexico City with a sign that says 'Authentic Tacos al Pastor'",
    "Craft market in Nairobi with a sign that says 'Masai Beadwork for Sale'",
    "Salsa club in Havana with a sign that says 'Live Cuban Music'",
    "Outdoor market in Marrakech with a sign that says 'Berber Carpets & Rugs'",
    "Garden in Kyoto with a sign that says 'Cherry Blossom Viewing Party'",
    "Piazza in Venice with a sign that says 'Italian Gelato Contest'",
    "Cultural center in Lima with a sign that says 'Peruvian Folk Dance Performance'",
    "Market in Istanbul with a sign that says 'Turkish Baklava Sampling'",
    "Teahouse in Shanghai with a sign that says 'Chinese Tea Ceremony'",
    "Plaza in Seville with a sign that says 'Flamenco Dance Show'",
    "Street market in Mumbai with a sign that says 'Colorful Indian Sarees'",
    "Bazaar in Istanbul with a sign that says 'Turkish Carpet Auction'",
    "Café in Buenos Aires with a sign that says 'Argentinian Tango Night'",
    "Street food stall in Bangkok with a sign that says 'Pad Thai Cooking Demo'",
    "Market in Cape Town with a sign that says 'South African Craft Fair'",
    "Night market in Hanoi with a sign that says 'Vietnamese Pho Challenge'",
    "Piazza in Rome with a sign that says 'Roman Pasta Making Workshop'",
    "Teahouse in Kyoto with a sign that says 'Matcha Tea Ceremony'",
    "Plaza in Mexico City with a sign that says 'Dia de los Muertos Celebration'",
    "Street market in Marrakech with a sign that says 'Moroccan Mint Tea Tasting'",
    "Café in Paris with a sign that says 'French Wine & Cheese Pairing'",
    "Night market in Seoul with a sign that says 'Korean Street Food Extravaganza'",
    "Market in Istanbul with a sign that says 'Turkish Delights Festival'"
]

SHORT_SIGNS3 = [
    "Local grocery store with a sign that says 'Fresh Produce Daily'",
    "Parent holding a sign that says 'School Zone, Slow Down'",
    "City park with a sign that says 'No Dogs Allowed'",
    "Coffee shop with a sign that says 'Open Mic Night Every Thursday'",
    "Protesters holding a sign that says 'Support Public Education'",
    "Library with a sign that says 'Book Donation Drive'",
    "Neighborhood market with a sign that says 'Community Yard Sale'",
    "Sports stadium with a sign that says 'Tickets Sold Out'",
    "College campus with a sign that says 'Student Art Exhibition'",
    "Artisan bakery with a sign that says 'Fresh Bread Baked Daily'",
    "Historic landmark with a sign that says 'Guided Tours Available'",
    "Public square with a sign that says 'Live Music Festival This Weekend'",
    "Local diner with a sign that says 'Breakfast Specials Until 11 AM'",
    "Animal shelter with a sign that says 'Adoption Event Saturday'",
    "Town hall with a sign that says 'Town Meeting Tonight at 7 PM'",
    "Gym with a sign that says 'New Year, New You: Sign Up Today'",
    "Local theater with a sign that says 'Auditions for Spring Play'",
    "Community garden with a sign that says 'Volunteers Needed'",
    "Medical clinic with a sign that says 'Flu Shots Available'",
    "Tech store with a sign that says 'Special Discount on Laptops'",
    "City transit with a sign that says 'Free Bus Rides for Seniors'",
    "Charity event with a sign that says 'Donate Blood, Save a Life'",
    "Public library with a sign that says 'Story Time for Kids'",
    "Fitness center with a sign that says 'Group Fitness Classes'",
    "Historical museum with a sign that says 'New Exhibit: Civil War Era'",
    "Food truck with a sign that says 'Taco Tuesday Special'",
    "Community center with a sign that says 'Teen Movie Night'",
    "Local pharmacy with a sign that says 'Drive-Thru Prescription Pickup'",
    "Farmers' market with a sign that says 'Organic, Locally Grown'",
    "Park entrance with a sign that says 'Picnic Area, No Alcohol'",
    "Pet adoption event with a sign that says 'Find Your New Best Friend'",
    "Outdoor concert venue with a sign that says 'Summer Concert Series'",
    "Bike rental shop with a sign that says 'Explore the City on Two Wheels'",
    "Recreation center with a sign that says 'Family Fun Day'",
    "Community pool with a sign that says 'Swim Lessons Available'",
    "Health fair with a sign that says 'Free Screenings and Consultations'",
    "Cultural festival with a sign that says 'Celebrating Diversity'",
    "Local craft brewery with a sign that says 'Live Music Tonight'",
    "City hall with a sign that says 'Register to Vote Here'",
    "Street fair with a sign that says 'Local Artists' Market'",
    "Town square with a sign that says 'Ice Cream Social This Saturday'",
    "Tech expo with a sign that says 'Discover the Latest Gadgets'",
    "Nature reserve with a sign that says 'Trail Closed for Maintenance'",
    "Community theater with a sign that says 'Matinee Performance'",
    "Food pantry with a sign that says 'Accepting Donations'",
    "Summer camp with a sign that says 'Early Bird Registration'",
    "Neighborhood association with a sign that says 'Annual Block Party'",
    "Local hardware store with a sign that says 'Weekend DIY Workshop'"
]

SHORT_SIGNS2 = [
    "Artisanal cheese shop with a sign that says 'Taste the Terroir'",
    "Secret speakeasy with a sign that says 'Password Required'",
    "Haunted mansion with a sign that says 'Beware of Ghosts'",
    "Alien spaceship with a sign that says 'Interstellar Welcome Center'",
    "Enchanted forest with a sign that says 'Beware of Pixies'",
    "Wizard's tower with a sign that says 'Magical Potions for Sale'",
    "Time-travel agency with a sign that says 'Explore the Past and Future'",
    "Underwater city with a sign that says 'Mermaid Sanctuary'",
    "Extraterrestrial diner with a sign that says 'Intergalactic Burgers'",
    "Fairy tale castle with a sign that says 'Royal Ball Tonight'",
    "Steampunk airship with a sign that says 'Mechanical Repairs'",
    "Apocalyptic wasteland with a sign that says 'Last Survivors Welcome'",
    "Jurassic park with a sign that says 'Dinosaur Feeding Time'",
    "Interdimensional portal with a sign that says 'Travel to Parallel Worlds'",
    "Haunted carnival with a sign that says 'Step Right Up to the Freak Show'",
    "Robot factory with a sign that says 'Assemble Your Own Bot'",
    "Witch's cauldron with a sign that says 'Potions Brewing'",
    "Vampire nightclub with a sign that says 'Blood Cocktails'",
    "Zombie apocalypse safe zone with a sign that says 'No Entry Without ID'",
    "Mad scientist's lab with a sign that says 'Experimental Inventions'",
    "Pirate ship with a sign that says 'Buried Treasure Here'",
    "Goblin market with a sign that says 'Trade Your Trinkets'",
    "Time-traveling train with a sign that says 'Next Stop: Ancient Rome'",
    "Magic carpet ride service with a sign that says 'Flying Tours'",
    "Ghost town with a sign that says 'Population: Ghosts'",
    "Space station with a sign that says 'Zero Gravity Yoga'",
    "Underground bunker with a sign that says 'Safe Haven'",
    "Enchanted library with a sign that says 'Books of Spells'",
    "Dragon sanctuary with a sign that says 'Enter at Your Own Risk'",
    "Futuristic cityscape with a sign that says 'Virtual Reality Arcade'",
    "Exotic pet shop with a sign that says 'Adopt a Dragon'",
    "Wizarding school with a sign that says 'Magical Lessons'",
    "Steampunk laboratory with a sign that says 'Inventor's Workshop'",
    "Robot uprising headquarters with a sign that says 'Join the Resistance'",
    "Fairytale village with a sign that says 'Happily Ever After Starts Here'",
    "Parallel universe swap meet with a sign that says 'Trade Your Reality'",
    "Haunted mansion with a sign that says 'Ghosts Only Beyond This Point'",
    "Underground dragon racing track with a sign that says 'Bets Accepted Here'",
    "Interstellar marketplace with a sign that says 'Trade Across Galaxies'",
    "Cyberpunk nightclub with a sign that says 'Neon Dreams'",
    "Vampire vineyard with a sign that says 'Blood Red Wine Tasting'",
    "Haunted theme park with a sign that says 'Nightmare Rides'",
    "Witch's apothecary with a sign that says 'Magical Ingredients for Sale'",
    "Fantasy tavern with a sign that says 'Ale and Adventure'",
    "Futuristic mall with a sign that says 'Cyber Shopping'",
    "Interdimensional cafe with a sign that says 'Quantum Coffee'",
    "Alien zoo with a sign that says 'Extraterrestrial Exhibits'",
    "Mad scientist's circus with a sign that says 'Unnatural Wonders'",
    "Time-traveling food truck with a sign that says 'Cuisine Across Centuries'",
]

SHORT_SIGNS = [
    "Street with a sign that says 'Support Local Businesses'",
    "Store with a sign that says 'Sale Today Only'",
    "Woman holding a sign that says 'Equal Pay for Equal Work'",
    "Children carrying a sign that says 'Save the Bees'",
    "Man holding a sign that says 'Climate Change is Real'",
    "Park with a sign that says 'Keep Off the Grass'",
    "Coffee shop with a sign that says 'Free WiFi'",
    "Protesters holding a sign that says 'End Police Brutality'",
    "Library with a sign that says 'Silence Please'",
    "Market with a sign that says 'Fresh Produce'",
    "Community center with a sign that says 'Volunteers Needed'",
    "Poster on a wall that says 'Art Exhibit Today'",
    "Gardens with a sign that says 'Do Not Pick the Flowers'",
    "Office building with a sign that says 'No Smoking'",
    "School with a sign that says 'Crosswalk Ahead'",
    "Billboard with a sign that says 'Vote for Change'",
    "Bus stop with a sign that says 'Next Bus Arrives in 10 Minutes'",
    "Hospital with a sign that says 'Emergency Room Entrance'",
    "Pet store with a sign that says 'Adopt, Don't Shop'",
    "Theater with a sign that says 'Now Showing: Blockbuster Movie'",
    "Restaurant with a sign that says 'Daily Specials'",
    "Church with a sign that says 'Sunday Service at 10 AM'",
    "Museum with a sign that says 'Exhibition Opening Tomorrow'",
    "Town hall with a sign that says 'Public Meeting Tonight'",
    "Beach with a sign that says 'No Lifeguard on Duty'",
    "Public restroom with a sign that says 'Out of Order'",
    "Skatepark with a sign that says 'Helmets Required'",
    "Petitioners holding a sign that says 'Save Our Forests'",
    "Street vendor with a sign that says 'Freshly Squeezed Juice'",
    "Subway station with a sign that says 'Mind the Gap'",
    "Zoo with a sign that says 'Feeding Time at 2 PM'",
    "Bakery with a sign that says 'Homemade Pies'",
    "Barbershop with a sign that says 'Walk-ins Welcome'",
    "Car dealership with a sign that says 'Year-End Clearance Sale'",
    "Construction site with a sign that says 'Hard Hat Area'",
    "Farmers' market with a sign that says 'Organic Produce'",
    "Ice cream parlor with a sign that says 'Buy One, Get One Free'",
    "Jewelry store with a sign that says '50% Off All Items'",
    "Police station with a sign that says 'Report Suspicious Activity'",
    "Playground with a sign that says 'Adults Must Be Accompanied by a Child'",
    "Post office with a sign that says 'Mail Drop Off'",
    "Train station with a sign that says 'Platform 3'",
    "University with a sign that says 'Student Orientation Today'",
    "Veterinary clinic with a sign that says 'Open 24 Hours'",
    "Fire station with a sign that says 'Emergency Services'",
    "Airport with a sign that says 'Baggage Claim'",
    "Bookstore with a sign that says 'Author Signing Event'",
    "Bowling alley with a sign that says 'Cosmic Bowling Tonight'",
    "Café with a sign that says 'Live Music Friday Night'",
    "Cinema with a sign that says 'Family Movie Matinee'",
    "Dentist office with a sign that says 'Free Teeth Cleaning'",
    "Gym with a sign that says 'New Member Special'",
    "Laundromat with a sign that says 'Wash and Fold Service Available'",
    "Library with a sign that says 'Book Sale Today'",
    "Nail salon with a sign that says 'Manicure and Pedicure Combo'",
    "Pharmacy with a sign that says 'Flu Shots Available'",
    "Pool with a sign that says 'No Diving'",
    "Tattoo parlor with a sign that says 'Custom Designs'",
    "Thrift store with a sign that says 'Half Price Clothing Sale'",
    "Toy store with a sign that says 'Holiday Toy Drive'",
    "Vape shop with a sign that says 'New Flavors In Stock'",
    "Wedding chapel with a sign that says 'Book Your Ceremony Today'",
    "Yoga studio with a sign that says 'Free Meditation Class'",
    "Art gallery with a sign that says 'Opening Reception'",
    "Burger joint with a sign that says 'Best Burgers in Town'",
    "Car wash with a sign that says 'Express Detailing'",
    "Comic book store with a sign that says 'Superhero Day'",
    "Craft store with a sign that says 'DIY Workshop'",
    "Doughnut shop with a sign that says 'Freshly Baked Daily'",
    "Furniture store with a sign that says 'Clearance Sale'",
    "Gift shop with a sign that says 'Unique Gifts for Every Occasion'",
    "Hardware store with a sign that says 'Grand Opening'",
    "Liquor store with a sign that says 'Wine Tasting Today'",
    "Maternity store with a sign that says 'Baby Shower Registry'",
    "Music store with a sign that says 'Instrument Rentals Available'",
    "Outdoor gear store with a sign that says 'End of Season Sale'",
    "Pawn shop with a sign that says 'Cash for Gold'",
    "Skate shop with a sign that says 'New Skateboard Models'",
    "Smoke shop with a sign that says 'Hookah Night'",
    "Tea shop with a sign that says 'Free Tea Tasting'",
    "Vintage clothing store with a sign that says 'Retro Fashion Show'",
    "Wine shop with a sign that says 'Wine and Cheese Pairing'",
    "Workout apparel store with a sign that says 'Athletic Gear Sale'",
    "Yarn store with a sign that says 'Knitting Circle Meetup'"
]

LONG_SCENES = [
    "A bustling city street corner with a protest group chanting slogans and waving handmade signs demanding climate action.",
    "A quaint bookstore nestled in a cobblestone alleyway, its display windows adorned with handwritten recommendations on colorful posters.",
    "A vibrant farmer's market brimming with fresh produce, each stall boasting hand-painted signs showcasing prices and origin details.",
    "A lively carnival midway, with colorful tents and rides illuminated by bright neon lights, and vendors selling treats with signs displaying enticing offers.",
    "A cozy cafe on a rainy afternoon, where patrons sit at wooden tables beneath handwritten chalkboard menus, sipping hot beverages and reading books.",
    "A bustling flea market under a sprawling tent, with vendors showcasing eclectic wares and antique treasures, each item accompanied by handwritten price tags.",
    "A bustling city square transformed into a lively protest rally, with passionate speakers addressing the crowd from a makeshift stage adorned with banners and posters.",
    "A charming street corner in a historic district, lined with quaint boutiques and cafes, their storefronts adorned with hand-painted signs and window displays.",
    "A lively street parade celebrating cultural diversity, with performers dressed in colorful costumes and floats adorned with elaborate handcrafted signage.",
    "A serene countryside road flanked by lush greenery and quaint roadside stands, each offering fresh produce and homemade goods with rustic handwritten signs.",
    "A bustling urban market packed with food stalls, where vendors advertise their specialties with vibrant, hand-painted signs and enthusiastic calls.",
    "A peaceful park transformed into a vibrant protest gathering, with demonstrators of all ages holding up signs with powerful messages advocating for equality.",
    "A picturesque coastal boardwalk lined with charming beachside cafes, their outdoor seating areas decorated with handwritten chalkboard menus and fairy lights.",
    "A festive street festival in full swing, with vendors selling handmade crafts and street food under colorful canopies adorned with hand-painted signs.",
    "A lively city square transformed into a bustling protest hub, with activists gathering around a central monument, holding up banners and chanting slogans.",
    "A bustling city street corner during rush hour, with commuters passing by colorful graffiti walls adorned with political messages and protest art.",
    "A quaint village fairground bustling with activity, with stalls offering homemade goods and games, each adorned with whimsical handcrafted signs.",
    "A lively urban market buzzing with activity, where vendors showcase their goods under colorful umbrellas, each stall adorned with handwritten signs.",
    "A vibrant street parade celebrating cultural heritage, with performers adorned in traditional attire and floats decorated with intricate hand-painted signage.",
    "A bustling city plaza transformed into a lively protest gathering, with demonstrators holding up signs and banners advocating for social justice.",
    "A charming street corner in a bustling neighborhood, with cafes and shops adorned with colorful banners and hand-painted signs welcoming visitors.",
    "A lively night market filled with the aroma of street food, where vendors advertise their specialties with colorful banners and handwritten signs.",
    "A picturesque countryside market day, with farmers selling fresh produce under a canopy of trees, each stall decorated with rustic handwritten signs.",
    "A bustling city street corner transformed into a vibrant protest rally, with activists of all ages holding up signs and banners demanding change.",
    "A serene coastal promenade lined with quaint beachside cafes, their outdoor seating areas decorated with handwritten chalkboard menus and fairy lights.",
    "A festive street fair in full swing, with vendors offering handmade crafts and local delicacies under colorful tents adorned with hand-painted signs.",
    "A lively city square buzzing with activity, where protesters gather around a central fountain, holding up signs with powerful messages advocating for peace.",
    "A bustling urban alleyway filled with street art and murals, each wall adorned with colorful graffiti and thought-provoking political messages.",
    "A quaint village marketplace bustling with activity, with stalls selling fresh produce and artisanal goods, each adorned with whimsical handcrafted signs.",
    "A lively urban bazaar filled with the hustle and bustle of shoppers, where vendors showcase their wares under vibrant awnings, each stall adorned with handwritten signs.",
    "A vibrant street procession celebrating cultural diversity, with participants dressed in elaborate costumes and floats adorned with intricate hand-painted signage.",
    "A bustling city square transformed into a vibrant protest hub, with activists gathering around a central monument, holding up banners and chanting slogans for change.",
    "A charming street corner in a historic district, with cafes and boutiques adorned with colorful banners and hand-painted signs welcoming visitors.",
    "A lively night market filled with the buzz of activity, where vendors advertise their specialties with colorful banners and hand-painted signs illuminated by twinkling lights.",
    "A picturesque countryside market day, with farmers selling fresh produce and homemade goods under the shade of towering trees, each stall adorned with rustic handwritten signs.",
    "A bustling city street corner transformed into a vibrant protest rally, with activists of all ages holding up signs and banners demanding action on environmental issues.",
    "A serene coastal promenade lined with quaint beachside cafes, their outdoor seating areas decorated with handwritten chalkboard menus and twinkling fairy lights.",
    "A festive street fair in full swing, with vendors offering handmade crafts and local delicacies under colorful canopies adorned with hand-painted signs.",
    "A lively city square buzzing with activity, where protesters gather around a central fountain, holding up signs with powerful messages advocating for social equality.",
    "A bustling urban alleyway filled with vibrant street art and murals, each wall adorned with colorful graffiti and thought-provoking political messages.",
    "A quaint village marketplace bustling with activity, with stalls selling fresh produce and artisanal goods, each adorned with whimsical handcrafted signs.",
    "A lively urban bazaar filled with the hustle and bustle of shoppers, where vendors showcase their wares under vibrant awnings, each stall adorned with handwritten signs.",
    "A vibrant street procession celebrating cultural diversity, with participants dressed in elaborate costumes and floats adorned with intricate hand-painted signage.",
    "A bustling city square transformed into a vibrant protest hub, with activists gathering around a central monument, holding up banners and chanting slogans for change.",
    "A charming street corner in a historic district, with cafes and boutiques adorned with colorful banners and hand-painted signs welcoming visitors.",
    "A lively night market filled with the buzz of activity, where vendors advertise their specialties with colorful banners and hand-painted signs illuminated by twinkling lights.",
    "A picturesque countryside market day, with farmers selling fresh produce and homemade goods under the shade of towering trees, each stall adorned with rustic handwritten signs.",
    "A bustling city street corner transformed into a vibrant protest rally, with activists of all ages holding up signs and banners demanding action on environmental issues.",
    "A serene coastal promenade lined with quaint beachside cafes, their outdoor seating areas decorated with handwritten chalkboard menus and twinkling fairy lights.",
    "A festive street fair in full swing, with vendors offering handmade crafts and local delicacies under colorful canopies adorned with hand-painted signs.",
    "A lively city square buzzing with activity, where protesters gather around a central fountain, holding up signs with powerful messages advocating for social equality.",
    "A bustling urban alleyway filled with vibrant street art and murals, each wall adorned with colorful graffiti and thought-provoking political messages.",
    "A quaint village marketplace bustling with activity, with stalls selling fresh produce and artisanal goods, each adorned with whimsical handcrafted signs.",
    "A lively urban bazaar filled with the hustle and bustle of shoppers, where vendors showcase their wares under vibrant awnings, each stall adorned with handwritten signs.",
    "A vibrant street procession celebrating cultural diversity, with participants dressed in elaborate costumes and floats adorned with intricate hand-painted signage.",
    "A bustling city square transformed into a vibrant protest hub, with activists gathering around a central monument, holding up banners and chanting slogans for change.",
    "A charming street corner in a historic district, with cafes and boutiques adorned with colorful banners and hand-painted signs welcoming visitors.",
    "A lively night market filled with the buzz of activity, where vendors advertise their specialties with colorful banners and hand-painted signs illuminated by twinkling lights.",
    "A picturesque countryside market day, with farmers selling fresh produce and homemade goods under the shade of towering trees, each stall adorned with rustic handwritten signs.",
    "A bustling city street corner transformed into a vibrant protest rally, with activists of all ages holding up signs and banners demanding action on environmental issues.",
    "A serene coastal promenade lined with quaint beachside cafes, their outdoor seating areas decorated with handwritten chalkboard menus and twinkling fairy lights.",
    "A festive street fair in full swing, with vendors offering handmade crafts and local delicacies under colorful canopies adorned with hand-painted signs.",
    "A lively city square buzzing with activity, where protesters gather around a central fountain, holding up signs with powerful messages advocating for social equality.",
    "A bustling urban alleyway filled with vibrant street art and murals, each wall adorned with colorful graffiti and thought-provoking political messages.",
    "A quaint village marketplace bustling with activity, with stalls selling fresh produce and artisanal goods, each adorned with whimsical handcrafted signs.",
    "A lively urban bazaar filled with the hustle and bustle of shoppers, where vendors showcase their wares under vibrant awnings, each stall adorned with handwritten signs.",
    "A vibrant street procession celebrating cultural diversity, with participants dressed in elaborate costumes and floats adorned with intricate hand-painted signage.",
    "A bustling city square transformed into a vibrant protest hub, with activists gathering around a central monument, holding up banners and chanting slogans for change.",
    "A charming street corner in a historic district, with cafes and boutiques adorned with colorful banners and hand-painted signs welcoming visitors.",
    "A lively night market filled with the buzz of activity, where vendors advertise their specialties with colorful banners and hand-painted signs illuminated by twinkling lights.",
    "A picturesque countryside market day, with farmers selling fresh produce and homemade goods under the shade of towering trees, each stall adorned with rustic handwritten signs.",
    "A bustling city street corner transformed into a vibrant protest rally, with activists of all ages holding up signs and banners demanding action on environmental issues.",
    "A serene coastal promenade lined with quaint beachside cafes, their outdoor seating areas decorated with handwritten chalkboard menus and twinkling fairy lights.",
    "A festive street fair in full swing, with vendors offering handmade crafts and local delicacies under colorful canopies adorned with hand-painted signs.",
    "A lively city square buzzing with activity, where protesters gather around a central fountain, holding up signs with powerful messages advocating for social equality.",
    "A bustling urban alleyway filled with vibrant street art and murals, each wall adorned with colorful graffiti and thought-provoking political messages.",
    "A quaint village marketplace bustling with activity, with stalls selling fresh produce and artisanal goods, each adorned with whimsical handcrafted signs.",
    "A lively urban bazaar filled with the hustle and bustle of shoppers, where vendors showcase their wares under vibrant awnings, each stall adorned with handwritten signs.",
    "A vibrant street procession celebrating cultural diversity, with participants dressed in elaborate costumes and floats adorned with intricate hand-painted signage.",
    "A bustling city square transformed into a vibrant protest hub, with activists gathering around a central monument, holding up banners and chanting slogans for change.",
    "A charming street corner in a historic district, with cafes and boutiques adorned with colorful banners and hand-painted signs welcoming visitors.",
    "A lively night market filled with the buzz of activity, where vendors advertise their specialties with colorful banners and hand-painted signs illuminated by twinkling lights.",
    "A picturesque countryside market day, with farmers selling fresh produce and homemade goods under the shade of towering trees, each stall adorned with rustic handwritten signs.",
    "A bustling city street corner transformed into a vibrant protest rally, with activists of all ages holding up signs and banners demanding action on environmental issues.",
    "A serene coastal promenade lined with quaint beachside cafes, their outdoor seating areas decorated with handwritten chalkboard menus and twinkling fairy lights.",
    "A festive street fair in full swing, with vendors offering handmade crafts and local delicacies under colorful canopies adorned with hand-painted signs.",
    "A lively city square buzzing with activity, where protesters gather around a central fountain, holding up signs with powerful messages advocating for social equality.",
    "A bustling urban alleyway filled with vibrant street art and murals, each wall adorned with colorful graffiti and thought-provoking political messages.",
    "A quaint village marketplace bustling with activity, with stalls selling fresh produce and artisanal goods, each adorned with whimsical handcrafted signs.",
    "A lively urban bazaar filled with the hustle and bustle of shoppers, where vendors showcase their wares under vibrant awnings, each stall adorned with handwritten signs.",
    "A vibrant street procession celebrating cultural diversity, with participants dressed in elaborate costumes and floats adorned with intricate hand-painted signage.",
    "A bustling city square transformed into a vibrant protest hub, with activists gathering around a central monument, holding up banners and chanting slogans for change.",
    "A charming street corner in a historic district, with cafes and boutiques adorned with colorful banners and hand-painted signs welcoming visitors.",
    "A lively night market filled with the buzz of activity, where vendors advertise their specialties with colorful banners and hand-painted signs illuminated by twinkling lights.",
    "A picturesque countryside market day, with farmers selling fresh produce and homemade goods under the shade of towering trees, each stall adorned with rustic handwritten signs.",
    "A bustling city street corner transformed into a vibrant protest rally, with activists of all ages holding up signs and banners demanding action on environmental issues.",
    "A serene coastal promenade lined with quaint beachside cafes, their outdoor seating areas decorated with handwritten chalkboard menus and twinkling fairy lights.",
    "A festive street fair in full swing, with vendors offering handmade crafts and local delicacies under colorful canopies adorned with hand-painted signs.",
    "A lively city square buzzing with activity, where protesters gather around a central fountain, holding up signs with powerful messages advocating for social equality.",
    "A bustling urban alleyway filled with vibrant street art and murals, each wall adorned with colorful graffiti and thought-provoking political messages.",
    "A quaint village marketplace bustling with activity, with stalls selling fresh produce and artisanal goods, each adorned with whimsical handcrafted signs.",
    "A lively urban bazaar filled with the hustle and bustle of shoppers, where vendors showcase their wares under vibrant awnings, each stall adorned with handwritten signs.",
    "A vibrant street procession celebrating cultural diversity, with participants dressed in elaborate costumes and floats adorned with intricate hand-painted signage.",
    "A bustling city square transformed into a vibrant protest hub, with activists gathering around a central monument, holding up banners and chanting slogans for change.",
]
